### ISSUE TITLE
decoding of timing bytes fails when timestamp is not valid.

### ISSUE THREAD

**Issue by StuartLittlefair** [trmrsh/hipercam#1]
If data is taken with the GPS flag in the eso software set to false, the timing bytes header is ```(0, 0, 0, 0, 0, 0, 0, 0, -1, -1)```

In this case, parsing the time string into an ```astropy.time.Time``` object will fail.

**Comment by trmrsh** [comment]
Stu, do you have a little test data file of this case so I can cook up a fix?

**Comment by trmrsh** [comment]
OK, I have added some code that checks for the last two -1 values (hope they reliable as a flag) and then just generates a time on 01-Jan-2000, 1 frame per sec. I have also added a header parameter GOODTIM. I have pushed it to github
